In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

# 1. This dataset reflects the crime incidents that occurred in San Francisco from 2003 to May 2018. Source: https://data.sfgov.org/Public-Safety/Police-Department-Incident-Reports-Historical-2003/tmnf-yvry

In [8]:
# import the dataset
p1 = pd.read_csv('datasets/major/Police_Department_Incident_Reports__Historical_2003_to_May_2018.csv')
p1.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,...,:@computed_region_n4xg_c4py,:@computed_region_4isq_27mq,:@computed_region_fcz8_est8,:@computed_region_pigm_ib2e,:@computed_region_9jxd_iqea,:@computed_region_6pnf_4xz7,:@computed_region_6ezc_tdp2,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_2dwj_jsy4
0,180362289,VEHICLE THEFT,STOLEN MOTORCYCLE,Tuesday,05/15/2018,10:30,SOUTHERN,NONE,700 Block of TEHAMA ST,-122.411912,...,1.0,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN
1,180360948,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Tuesday,05/15/2018,04:14,SOUTHERN,NONE,MARKET ST / SOUTH VAN NESS AV,-122.419258,...,1.0,NaN,1.0,NaN,8.0,2.0,1.0,1.0,1.0,NaN
2,180360879,OTHER OFFENSES,PAROLE VIOLATION,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,...,NaN,15.0,3.0,15.0,NaN,2.0,NaN,NaN,3.0,NaN
3,180360879,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,...,NaN,15.0,3.0,15.0,NaN,2.0,NaN,NaN,3.0,NaN
4,180360879,OTHER OFFENSES,TRAFFIC VIOLATION,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,...,NaN,15.0,3.0,15.0,NaN,2.0,NaN,NaN,3.0,NaN

In [52]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215024 entries, 0 to 2215023
Data columns (total 33 columns):
IncidntNum                      int64
Category                        object
Descript                        object
DayOfWeek                       object
Date                            object
Time                            object
PdDistrict                      object
Resolution                      object
Address                         object
X                               float64
Y                               float64
Location                        object
PdId                            int64
SF Find Neighborhoods           float64
Current Police Districts        float64
Current Supervisor Districts    float64
Analysis Neighborhoods          float64
:@computed_region_yftq_j783     float64
:@computed_region_p5aj_wyqh     float64
:@computed_region_rxqg_mtj9     float64
:@computed_region_bh8s_q3mv     float64
:@computed_region_fyvs_ahh9     float64
:@computed_region_9dfj_4gjx     float64
:@computed_region_n4xg_c4py     float64
:@computed_region_4isq_27mq     float64
:@computed_region_fcz8_est8     float64
:@computed_region_pigm_ib2e     float64
:@computed_region_9jxd_iqea     float64
:@computed_region_6pnf_4xz7     float64
:@computed_region_6ezc_tdp2     float64
:@computed_region_h4ep_8xdi     float64
:@computed_region_nqbw_i6c3     float64
:@computed_region_2dwj_jsy4     float64
dtypes: float64(22), int64(2), object(9)
memory usage: 557.7+ MB

In [53]:
# see column names
p1.columns

Index(['IncidntNum', 'Category', 'Descript', 'DayOfWeek', 'Date', 'Time',
       'PdDistrict', 'Resolution', 'Address', 'X', 'Y', 'Location', 'PdId',
       'SF Find Neighborhoods', 'Current Police Districts',
       'Current Supervisor Districts', 'Analysis Neighborhoods',
       ':@computed_region_yftq_j783', ':@computed_region_p5aj_wyqh',
       ':@computed_region_rxqg_mtj9', ':@computed_region_bh8s_q3mv',
       ':@computed_region_fyvs_ahh9', ':@computed_region_9dfj_4gjx',
       ':@computed_region_n4xg_c4py', ':@computed_region_4isq_27mq',
       ':@computed_region_fcz8_est8', ':@computed_region_pigm_ib2e',
       ':@computed_region_9jxd_iqea', ':@computed_region_6pnf_4xz7',
       ':@computed_region_6ezc_tdp2', ':@computed_region_h4ep_8xdi',
       ':@computed_region_nqbw_i6c3', ':@computed_region_2dwj_jsy4'],
      dtype='object')

In [54]:
# see number of rows and columns
p1.shape

(2215024, 33)

In [55]:
p1.isnull().sum()

IncidntNum                            0
Category                              0
Descript                              0
DayOfWeek                             0
Date                                  0
Time                                  0
PdDistrict                            1
Resolution                            0
Address                               0
X                                     0
Y                                     0
Location                              0
PdId                                  0
SF Find Neighborhoods              6077
Current Police Districts           1112
Current Supervisor Districts        661
Analysis Neighborhoods             1057
:@computed_region_yftq_j783        5580
:@computed_region_p5aj_wyqh        1523
:@computed_region_rxqg_mtj9         661
:@computed_region_bh8s_q3mv         495
:@computed_region_fyvs_ahh9        1057
:@computed_region_9dfj_4gjx     1666617
:@computed_region_n4xg_c4py     1894819
:@computed_region_4isq_27mq     1650528
:@computed_region_fcz8_est8     1741230
:@computed_region_pigm_ib2e     1644859
:@computed_region_9jxd_iqea     1650003
:@computed_region_6pnf_4xz7        1057
:@computed_region_6ezc_tdp2     1874086
:@computed_region_h4ep_8xdi     1873898
:@computed_region_nqbw_i6c3     1711576
:@computed_region_2dwj_jsy4     2095933
dtype: int64

## As the most fields in ":computed_region_" columns are null values, we remove these columns below by dropping them.

In [56]:
# remove irrelevant columns
p1.drop(['PdId',
        ':@computed_region_yftq_j783', 
         ':@computed_region_p5aj_wyqh',
         ':@computed_region_rxqg_mtj9',
        ':@computed_region_bh8s_q3mv', 
        ':@computed_region_fyvs_ahh9',
        ':@computed_region_9dfj_4gjx',
        ':@computed_region_n4xg_c4py',
        ':@computed_region_4isq_27mq',
        ':@computed_region_fcz8_est8',
        ':@computed_region_pigm_ib2e',
        ':@computed_region_9jxd_iqea',
        ':@computed_region_6pnf_4xz7',
        ':@computed_region_6ezc_tdp2',
        ':@computed_region_h4ep_8xdi',
        ':@computed_region_nqbw_i6c3',
        ':@computed_region_2dwj_jsy4'], axis=1, inplace=True)
p1.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods
0,180362289,VEHICLE THEFT,STOLEN MOTORCYCLE,Tuesday,05/15/2018,10:30,SOUTHERN,NONE,700 Block of TEHAMA ST,-122.411912,37.775207,"(37.77520656149669, -122.41191202732877)",32.0,1.0,10.0,34.0
1,180360948,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Tuesday,05/15/2018,04:14,SOUTHERN,NONE,MARKET ST / SOUTH VAN NESS AV,-122.419258,37.775146,"(37.77514629165388, -122.41925789481357)",32.0,1.0,10.0,20.0
2,180360879,OTHER OFFENSES,PAROLE VIOLATION,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,37.757101,"(37.757100579642824, -122.41781255878655)",53.0,3.0,2.0,20.0
3,180360879,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,37.757101,"(37.757100579642824, -122.41781255878655)",53.0,3.0,2.0,20.0
4,180360879,OTHER OFFENSES,TRAFFIC VIOLATION,Tuesday,05/15/2018,02:01,MISSION,"ARREST, BOOKED",CAPP ST / 21ST ST,-122.417813,37.757101,"(37.757100579642824, -122.41781255878655)",53.0,3.0,2.0,20.0

In [57]:
# convert p1['date'] from string to datetime
p1['Date'] = pd.to_datetime(p1['Date'])
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215024 entries, 0 to 2215023
Data columns (total 16 columns):
IncidntNum                      int64
Category                        object
Descript                        object
DayOfWeek                       object
Date                            datetime64[ns]
Time                            object
PdDistrict                      object
Resolution                      object
Address                         object
X                               float64
Y                               float64
Location                        object
SF Find Neighborhoods           float64
Current Police Districts        float64
Current Supervisor Districts    float64
Analysis Neighborhoods          float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(8)
memory usage: 270.4+ MB

## Extract crime cases from from 2003 to 2017 from this dataset.

In [58]:
p2003_2017 = p1[p1['Date'].dt.year < 2018]
p2003_2017.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods
46668,180000417,ASSAULT,BATTERY,Sunday,2017-12-31,23:58,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.40340479147905)",32.0,1.0,10.0,34.0
46669,180000069,ASSAULT,AGGRAVATED ASSAULT WITH A KNIFE,Sunday,2017-12-31,23:56,TENDERLOIN,"ARREST, BOOKED",500 Block of JONES ST,-122.412999,37.786277,"(37.78627745916602, -122.41299907500884)",20.0,5.0,10.0,36.0
46670,180000069,BURGLARY,"BURGLARY OF APARTMENT HOUSE, FORCIBLE ENTRY",Sunday,2017-12-31,23:56,TENDERLOIN,"ARREST, BOOKED",500 Block of JONES ST,-122.412999,37.786277,"(37.78627745916602, -122.41299907500884)",20.0,5.0,10.0,36.0
46671,180000069,WEAPON LAWS,EXHIBITING DEADLY WEAPON IN A THREATING MANNER,Sunday,2017-12-31,23:56,TENDERLOIN,"ARREST, BOOKED",500 Block of JONES ST,-122.412999,37.786277,"(37.78627745916602, -122.41299907500884)",20.0,5.0,10.0,36.0
46672,186005077,LARCENY/THEFT,PETTY THEFT OF PROPERTY,Sunday,2017-12-31,23:55,MISSION,NONE,500 Block of VALENCIA ST,-122.421876,37.764089,"(37.76408889445322, -122.42187648849193)",37.0,3.0,5.0,20.0

In [59]:
p2003_2017.shape

(2168356, 16)

# 2. This dataset reflects the crime incidents that occurred in San Francisco from 1/1/2018 to 4/18/2019. Source: https://catalog.data.gov/dataset/police-department-incident-reports-2018-to-present

In [68]:
# import dataset
p2 = pd.read_csv('datasets/major/Police_Department_Incident_Reports__2018_to_Present.csv')
p2.head()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,point,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,HSOC Zones as of 2018-06-05,OWED Public Spaces,Central Market/Tenderloin Boundary Polygon - Updated,Parks Alliance CPSI (27+TL sites)
0,2018/12/02 12:45:00 AM,2018/12/02,00:45,2018,Sunday,2018/12/02 01:56:00 AM,74374327130,743743,180908554,183360210.0,...,-122.404795,"(37.78490829943, -122.40479506276)",32.0,5.0,10.0,8.0,NaN,NaN,NaN,NaN
1,2018/12/01 08:30:00 PM,2018/12/01,20:30,2018,Saturday,2018/12/01 09:18:00 PM,74370071000,743700,180908112,183353564.0,...,-122.408036,"(37.786409612811, -122.408036237445)",19.0,6.0,3.0,36.0,NaN,NaN,1.0,NaN
2,2019/03/18 02:01:00 PM,2019/03/18,14:01,2019,Monday,2019/03/18 02:21:00 PM,78164004134,781640,190194129,190772267.0,...,-122.406699,"(37.756833733806, -122.406699002688)",53.0,3.0,2.0,20.0,3.0,NaN,NaN,NaN
3,2019/03/20 08:00:00 AM,2019/03/20,08:00,2019,Wednesday,2019/03/20 02:06:00 PM,78169706244,781697,190199583,190792201.0,...,-122.404865,"(37.78400661242, -122.404864795177)",32.0,1.0,10.0,34.0,NaN,NaN,NaN,NaN
4,2019/03/12 01:30:00 PM,2019/03/12,13:30,2019,Tuesday,2019/03/15 06:02:00 PM,78154706372,781547,196055103,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
p2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194356 entries, 0 to 194355
Data columns (total 34 columns):
Incident Datetime                                       194356 non-null object
Incident Date                                           194356 non-null object
Incident Time                                           194356 non-null object
Incident Year                                           194356 non-null int64
Incident Day of Week                                    194356 non-null object
Report Datetime                                         194356 non-null object
Row ID                                                  194356 non-null int64
Incident ID                                             194356 non-null int64
Incident Number                                         194356 non-null int64
CAD Number                                              149783 non-null float64
Report Type Code                                        194356 non-null object
Report Type Description                                 194356 non-null object
Filed Online                                            41689 non-null object
Incident Code                                           194356 non-null int64
Incident Category                                       194339 non-null object
Incident Subcategory                                    194339 non-null object
Incident Description                                    194356 non-null object
Resolution                                              194356 non-null object
Intersection                                            183893 non-null object
CNN                                                     183893 non-null float64
Police District                                         194356 non-null object
Analysis Neighborhood                                   183840 non-null object
Supervisor District                                     183893 non-null float64
Latitude                                                183893 non-null float64
Longitude                                               183893 non-null float64
point                                                   183893 non-null object
SF Find Neighborhoods                                   180068 non-null float64
Current Police Districts                                183585 non-null float64
Current Supervisor Districts                            183862 non-null float64
Analysis Neighborhoods                                  183809 non-null float64
HSOC Zones as of 2018-06-05                             44098 non-null float64
OWED Public Spaces                                      9960 non-null float64
Central Market/Tenderloin Boundary Polygon - Updated    26070 non-null float64
Parks Alliance CPSI (27+TL sites)                       2447 non-null float64
dtypes: float64(13), int64(5), object(16)
memory usage: 50.4+ MB

In [70]:
# show all column names
p2.columns

Index(['Incident Datetime', 'Incident Date', 'Incident Time', 'Incident Year',
       'Incident Day of Week', 'Report Datetime', 'Row ID', 'Incident ID',
       'Incident Number', 'CAD Number', 'Report Type Code',
       'Report Type Description', 'Filed Online', 'Incident Code',
       'Incident Category', 'Incident Subcategory', 'Incident Description',
       'Resolution', 'Intersection', 'CNN', 'Police District',
       'Analysis Neighborhood', 'Supervisor District', 'Latitude', 'Longitude',
       'point', 'SF Find Neighborhoods', 'Current Police Districts',
       'Current Supervisor Districts', 'Analysis Neighborhoods',
       'HSOC Zones as of 2018-06-05', 'OWED Public Spaces',
       'Central Market/Tenderloin Boundary Polygon - Updated',
       'Parks Alliance CPSI (27+TL sites)'],
      dtype='object')

In [71]:
p2.shape

(194356, 34)

In [72]:
p2.isnull().sum()

Incident Datetime                                            0
Incident Date                                                0
Incident Time                                                0
Incident Year                                                0
Incident Day of Week                                         0
Report Datetime                                              0
Row ID                                                       0
Incident ID                                                  0
Incident Number                                              0
CAD Number                                               44573
Report Type Code                                             0
Report Type Description                                      0
Filed Online                                            152667
Incident Code                                                0
Incident Category                                           17
Incident Subcategory                                        17
Incident Description                                         0
Resolution                                                   0
Intersection                                             10463
CNN                                                      10463
Police District                                              0
Analysis Neighborhood                                    10516
Supervisor District                                      10463
Latitude                                                 10463
Longitude                                                10463
point                                                    10463
SF Find Neighborhoods                                    14288
Current Police Districts                                 10771
Current Supervisor Districts                             10494
Analysis Neighborhoods                                   10547
HSOC Zones as of 2018-06-05                             150258
OWED Public Spaces                                      184396
Central Market/Tenderloin Boundary Polygon - Updated    168286
Parks Alliance CPSI (27+TL sites)                       191909
dtype: int64

In [73]:
# remove irrelavant columns
p2.drop(['Incident Datetime', 'Incident Year', 'Report Datetime', 'Filed Online', 'Row ID', 'Incident ID', 
         'CAD Number', 'Report Type Code', 'Report Type Description', 'Incident Code', 'CNN', 
         'HSOC Zones as of 2018-06-05', 'OWED Public Spaces', 'Incident Subcategory',
        'Central Market/Tenderloin Boundary Polygon - Updated', 'Supervisor District','Analysis Neighborhood',
        'Parks Alliance CPSI (27+TL sites)'], axis=1, inplace=True)
p2.head()

,Incident Date,Incident Time,Incident Day of Week,Incident Number,Incident Category,Incident Description,Resolution,Intersection,Police District,Latitude,Longitude,point,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods
0,2018/12/02,00:45,Sunday,180908554,Other Miscellaneous,"Burglary Tools, Possession Of",Cite or Arrest Adult,04TH ST \ JESSIE ST,Southern,37.784908,-122.404795,"(37.78490829943, -122.40479506276)",32.0,5.0,10.0,8.0
1,2018/12/01,20:30,Saturday,180908112,Lost Property,Lost Property,Open or Active,POWELL ST \ OFARRELL ST,Central,37.786410,-122.408036,"(37.786409612811, -122.408036237445)",19.0,6.0,3.0,36.0
2,2019/03/18,14:01,Monday,190194129,Assault,Battery,Cite or Arrest Adult,22ND ST \ POTRERO AVE,Mission,37.756834,-122.406699,"(37.756833733806, -122.406699002688)",53.0,3.0,2.0,20.0
3,2019/03/20,08:00,Wednesday,190199583,Larceny Theft,"Theft, From Locked Vehicle, >$950",Open or Active,JESSIE EAST ST \ MISSION ST,Southern,37.784007,-122.404865,"(37.78400661242, -122.404864795177)",32.0,1.0,10.0,34.0
4,2019/03/12,13:30,Tuesday,196055103,Larceny Theft,"Theft, Other Property, $50-$200",Open or Active,NaN,Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
p2.shape

(194356, 16)

In [76]:
# change column names to be consistent with p1
p2.columns = ['Date', 'Time', 'DayOfWeek', 'IncidntNum', 'Category', 'Descript', 'Resolution',
              'Address', 'PdDistrict', 'Y', 'X', 'Location', 'SF Find Neighborhoods', 
              'Current Police Districts',  'Current Supervisor Districts', 'Analysis Neighborhoods']
p2.head()

,Date,Time,DayOfWeek,IncidntNum,Category,Descript,Resolution,Address,PdDistrict,Y,X,Location,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods
0,2018/12/02,00:45,Sunday,180908554,Other Miscellaneous,"Burglary Tools, Possession Of",Cite or Arrest Adult,04TH ST \ JESSIE ST,Southern,37.784908,-122.404795,"(37.78490829943, -122.40479506276)",32.0,5.0,10.0,8.0
1,2018/12/01,20:30,Saturday,180908112,Lost Property,Lost Property,Open or Active,POWELL ST \ OFARRELL ST,Central,37.786410,-122.408036,"(37.786409612811, -122.408036237445)",19.0,6.0,3.0,36.0
2,2019/03/18,14:01,Monday,190194129,Assault,Battery,Cite or Arrest Adult,22ND ST \ POTRERO AVE,Mission,37.756834,-122.406699,"(37.756833733806, -122.406699002688)",53.0,3.0,2.0,20.0
3,2019/03/20,08:00,Wednesday,190199583,Larceny Theft,"Theft, From Locked Vehicle, >$950",Open or Active,JESSIE EAST ST \ MISSION ST,Southern,37.784007,-122.404865,"(37.78400661242, -122.404864795177)",32.0,1.0,10.0,34.0
4,2019/03/12,13:30,Tuesday,196055103,Larceny Theft,"Theft, Other Property, $50-$200",Open or Active,NaN,Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# convert p2['date'] from string to datetime
p2['Date'] = pd.to_datetime(p2['Date'])
p2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194356 entries, 0 to 194355
Data columns (total 16 columns):
Date                            194356 non-null datetime64[ns]
Time                            194356 non-null object
DayOfWeek                       194356 non-null object
IncidntNum                      194356 non-null int64
Category                        194339 non-null object
Descript                        194356 non-null object
Resolution                      194356 non-null object
Address                         183893 non-null object
PdDistrict                      194356 non-null object
Y                               183893 non-null float64
X                               183893 non-null float64
Location                        183893 non-null object
SF Find Neighborhoods           180068 non-null float64
Current Police Districts        183585 non-null float64
Current Supervisor Districts    183862 non-null float64
Analysis Neighborhoods          183809 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(8)
memory usage: 23.7+ MB

In [79]:
p_2018 = p2[p2['Date'].dt.year < 2019]
p_2018.head()

,Date,Time,DayOfWeek,IncidntNum,Category,Descript,Resolution,Address,PdDistrict,Y,X,Location,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods
0,2018-12-02,00:45,Sunday,180908554,Other Miscellaneous,"Burglary Tools, Possession Of",Cite or Arrest Adult,04TH ST \ JESSIE ST,Southern,37.784908,-122.404795,"(37.78490829943, -122.40479506276)",32.0,5.0,10.0,8.0
1,2018-12-01,20:30,Saturday,180908112,Lost Property,Lost Property,Open or Active,POWELL ST \ OFARRELL ST,Central,37.786410,-122.408036,"(37.786409612811, -122.408036237445)",19.0,6.0,3.0,36.0
52,2018-11-16,01:34,Friday,196076472,Larceny Theft,"Theft, Other Property, >$950",Open or Active,15TH ST \ SHOTWELL ST,Mission,37.766871,-122.416549,"(37.76687147079, -122.41654853899)",53.0,3.0,2.0,20.0
157,2018-08-19,23:00,Sunday,180625134,Larceny Theft,"Theft, From Locked Vehicle, >$950",Open or Active,FOLSOM ST \ SHERMAN ST,Southern,37.777400,-122.407015,"(37.777399632579, -122.407014752551)",32.0,1.0,10.0,34.0
216,2018-12-31,01:00,Monday,196076290,Larceny Theft,"Theft, From Locked Vehicle, >$950",Open or Active,NaN,Bayview,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 3. Combine the 2 datasets

In [82]:
# Combine the 2 datasets and reset the indexes
p00 = pd.concat([p2003_2017, p_2018], ignore_index=True)
p00.head()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Address,Analysis Neighborhoods,Category,Current Police Districts,Current Supervisor Districts,Date,DayOfWeek,Descript,IncidntNum,Location,PdDistrict,Resolution,SF Find Neighborhoods,Time,X,Y
0,800 Block of BRYANT ST,34.0,ASSAULT,1.0,10.0,2017-12-31,Sunday,BATTERY,180000417,"(37.775420706711, -122.40340479147905)",SOUTHERN,NONE,32.0,23:58,-122.403405,37.775421
1,500 Block of JONES ST,36.0,ASSAULT,5.0,10.0,2017-12-31,Sunday,AGGRAVATED ASSAULT WITH A KNIFE,180000069,"(37.78627745916602, -122.41299907500884)",TENDERLOIN,"ARREST, BOOKED",20.0,23:56,-122.412999,37.786277
2,500 Block of JONES ST,36.0,BURGLARY,5.0,10.0,2017-12-31,Sunday,"BURGLARY OF APARTMENT HOUSE, FORCIBLE ENTRY",180000069,"(37.78627745916602, -122.41299907500884)",TENDERLOIN,"ARREST, BOOKED",20.0,23:56,-122.412999,37.786277
3,500 Block of JONES ST,36.0,WEAPON LAWS,5.0,10.0,2017-12-31,Sunday,EXHIBITING DEADLY WEAPON IN A THREATING MANNER,180000069,"(37.78627745916602, -122.41299907500884)",TENDERLOIN,"ARREST, BOOKED",20.0,23:56,-122.412999,37.786277
4,500 Block of VALENCIA ST,20.0,LARCENY/THEFT,3.0,5.0,2017-12-31,Sunday,PETTY THEFT OF PROPERTY,186005077,"(37.76408889445322, -122.42187648849193)",MISSION,NONE,37.0,23:55,-122.421876,37.764089

In [84]:
p00.isnull().sum()

Address                          7894
Analysis Neighborhoods           8991
Category                           15
Current Police Districts         9233
Current Supervisor Districts     8563
Date                                0
DayOfWeek                           0
Descript                            0
IncidntNum                          0
Location                         7894
PdDistrict                          1
Resolution                          0
SF Find Neighborhoods           16811
Time                                0
X                                7894
Y                                7894
dtype: int64

In [86]:
p00.shape

(2322659, 16)

# to remove duplicated crime incidents by using 'IncidntNum' and keeping the first row of the duplicated ones and keep the 1st row when there's a duplicate as the category was listed in the order of severity.

In [87]:
p0 = p00.drop_duplicates('IncidntNum')
p0.head()

,Address,Analysis Neighborhoods,Category,Current Police Districts,Current Supervisor Districts,Date,DayOfWeek,Descript,IncidntNum,Location,PdDistrict,Resolution,SF Find Neighborhoods,Time,X,Y
0,800 Block of BRYANT ST,34.0,ASSAULT,1.0,10.0,2017-12-31,Sunday,BATTERY,180000417,"(37.775420706711, -122.40340479147905)",SOUTHERN,NONE,32.0,23:58,-122.403405,37.775421
1,500 Block of JONES ST,36.0,ASSAULT,5.0,10.0,2017-12-31,Sunday,AGGRAVATED ASSAULT WITH A KNIFE,180000069,"(37.78627745916602, -122.41299907500884)",TENDERLOIN,"ARREST, BOOKED",20.0,23:56,-122.412999,37.786277
4,500 Block of VALENCIA ST,20.0,LARCENY/THEFT,3.0,5.0,2017-12-31,Sunday,PETTY THEFT OF PROPERTY,186005077,"(37.76408889445322, -122.42187648849193)",MISSION,NONE,37.0,23:55,-122.421876,37.764089
5,700 Block of HARRISON ST,34.0,LARCENY/THEFT,1.0,10.0,2017-12-31,Sunday,PETTY THEFT OF PROPERTY,176001461,"(37.782137249161906, -122.3978145063337)",SOUTHERN,NONE,32.0,23:50,-122.397815,37.782137
6,HEMLOCK ST / POLK ST,21.0,DRUNKENNESS,4.0,3.0,2017-12-31,Sunday,UNDER INFLUENCE OF ALCOHOL IN A PUBLIC PLACE,180000025,"(37.787280707610776, -122.42002147104692)",NORTHERN,"ARREST, BOOKED",50.0,23:46,-122.420021,37.787281

In [88]:
p0.shape

(1822068, 16)

In [89]:
p0.isnull().sum()

Address                          6415
Analysis Neighborhoods           7276
Category                            8
Current Police Districts         7489
Current Supervisor Districts     6940
Date                                0
DayOfWeek                           0
Descript                            0
IncidntNum                          0
Location                         6415
PdDistrict                          1
Resolution                          0
SF Find Neighborhoods           13495
Time                                0
X                                6415
Y                                6415
dtype: int64

## Save the new merged dataset as "p0".

In [90]:
p0.to_csv('datasets/p0.csv')